FROM eclipse-temurin:17-jre-jammy

COPY agent/build/libs/agent-*.jar /app/agent.jar

EXPOSE 7070

ENTRYPOINT ["java", \
  "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED", \
  "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED", \
  "--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED", \
  "-jar", "/app/agent.jar"]
